name: azzaops_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ^3.11.5
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  get_storage: ^2.1.1
  image_picker: ^1.2.3
  cached_network_image: ^3.4.1
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.1.0
  http: ^1.6.0
  firebase_core: ^4.12.1
  url_launcher: ^6.3.2
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  ota_update: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ca/certificate.pem
